services:
  glances:
    image: docker.io/nicolargo/glances:latest
    container_name: glances
    ports: 
      - 61208:61208
      - 61209:61209
    volumes:
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /path/to/glances/:/config
      # Uncomment the below line if you want glances to display host OS detail instead of container's
      # - /etc/os-release:/etc/os-release:ro
    environment:
      - "GLANCES_OPT=-w"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  speedtest-tracker:
      container_name: speedtest-tracker
      ports:
          - 8787:80
          - 8443:443
      environment:
          - PUID=1000
          - PGID=1000
          - APP_KEY={seceretapikey}
          - DB_CONNECTION=sqlite
          - SPEEDTEST_SCHEDULE=00 * * * *
          - SPEEDTEST_SERVERS=
          - CHART_DATETIME_FORMAT=h:i a
          - DATETIME_FORMAT=h:i a
          - APP_TIMEZONE=America/New_York
          - DISPLAY_TIMEZONE=America/New_York
          - APP_DEBUG=true
      volumes:
          - /path/to//speedtest_tracker/config:/config
          - /path/to/speedtest_tracker/config/keys:/config/keys
      image: lscr.io/linuxserver/speedtest-tracker:latest
      restart: unless-stopped
       
