services:
#Plex Media Server
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
        - "32400:32400" 
    volumes:
        - /path/to/config:/config 
        - /path/to/temp:/transcode 
        - /path/to/media:/data 
    environment:
     PUID: 1000
     PGID: 1000
     TZ: America/New_York
