services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy:latest
    container_name: dashy
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
       - /home/jeremy/Server/configs/dashy/config.yml:/app/user-data/conf.yml
       - /home/jeremy/Server/configs/dashy/appdata/:/app/user-data/
    ports:
      - 4000:8080
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - PUID=1000
      - PGID=1000
    # Specify restart policy
    restart: unless-stopped
    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s